###Import required Library

In [1]:
import pandas as pd

###Load Data

In [2]:
df=pd.read_csv('/content/advertising-dataset .csv')

###Show the data

In [3]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

###Show data Types

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         204 non-null    float64
 1   Radio      203 non-null    float64
 2   Newspaper  202 non-null    float64
 3   Sales      204 non-null    float64
dtypes: float64(4)
memory usage: 6.5 KB

###Statistical Data

In [5]:
df.describe()

               TV       Radio   Newspaper       Sales
count  204.000000  203.000000  202.000000  204.000000
mean   147.096569   22.919212   30.516337   15.031863
std     85.005037   15.000253   21.669154    5.278091
min      0.700000    0.000000    0.300000    1.600000
25%     75.000000    9.450000   12.825000   10.875000
50%    149.800000   22.300000   25.600000   15.750000
75%    218.425000   36.400000   44.900000   18.925000
max    296.400000   49.600000  114.000000   27.000000

###Find Missing data

In [6]:
df.isnull().sum()

TV           0
Radio        1
Newspaper    2
Sales        0
dtype: int64

###Find Missing Value If yes Then replace by mean() value

In [14]:
# df["Radio"].isnull().sum()
df_cleaned=df['Radio'].fillna(df['Radio'].mean())
df['Radio']

# Check after Handle missing value
df["Radio"].isnull().sum()

np.int64(0)

###Find Duplicate value

In [22]:
# df.duplicated().sum()

df_cleaned=df.drop_duplicates()
# Drop Duplicates after cleaned
df_cleaned.duplicated().sum()

np.int64(0)

In [29]:
df_cleaned.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9